baseURL = "https://the-road-to-open-source.nextorange.top/"
title = "The Road to Open Source"
theme = "hugo-book"
languageCode = "zh-CN"

[outputs]
  home = ["HTML", "JSON"]

[params]
  BookTheme = "auto"
  BookToC = true
  BookMenuBundle = false
  BookSearch = true

[menu]
  [[menu.before]]
    name = "Intro"
    url = "/"
    weight = 1
  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/xczdev/open-source-with-fedora"
    weight = 1
